export const ADD_DATA = "ADD_DATA"
export const GET_HOTELS = "GET_HOTELS"
export const SET_HOTELS = "SET_HOTELS"
export const ADD_FAVORITE = "ADD_FAVORITE"
export const DELETE__FAVORITE = "DELETE__FAVORITE"
